### ISSUE TITLE
Tag stable releases

### ISSUE THREAD

**Issue by akien-mga** [wgois/OIS#26]
Please tag stable releases corresponding to the SourceForge tarballs (for the sake of history and traceability).

**Comment by Ybalrid** [comment]
This could be a neat thing to do. However, I'm not sure how easy it would be to track down `git commit <--> tarbal` correspondences as they where not using Git back then. 

Will take a look, but I can't promise anything...

**Comment by Ybalrid** [comment]
I'm tagging theses releases as best of my ability, but it looks like most of the history is lost anyway. This git repo was a botched import from SVN, and the history in SVN started only in 2010, so anything behind 1.3 doesn't exist on GitHub anyway.
