### ISSUE TITLE
Building as static lib for VS 2015 gives a CMake error

### ISSUE THREAD

**Issue by dagophil** [wgois/OIS#56]
Hello,

**Bug description:**
I am trying to build OIS on Windows 7 using the generator "Visual Studio 14 2015". Everything works fine if I leave all CMake Options on their default value. However, when I set `OIS_BUILD_SHARED_LIBS` to false, CMake fails with the following message:
```
CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:OIS>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.
```

**Steps to reproduce:**
```
git clone https://github.com/wgois/OIS
mkdir build
cd build
cmake -g "Visual Studio 14 2015" -DOIS_BUILD_SHARED_LIBS=0 ..\OIS
```

**Expected behavior:**
No CMake error.

**Platform:**
 - OS: Windows 7.
 - Backend: Not sure, probably DirectInput?
 - Version: Both latest master (commit 27c44b0) and release 1.5 fail, I did not test others.

**Additional context:**
I think the error comes from the following lines in CMakeLists.txt:
```
if(MSVC)
  install(FILES $<TARGET_PDB_FILE:OIS> DESTINATION bin OPTIONAL)
endif(MSVC)
```
According to [the CMake documentation](https://cmake.org/cmake/help/v3.15/manual/cmake-generator-expressions.7.html#target-dependent-queries) and [this CMake issue](https://gitlab.kitware.com/cmake/cmake/issues/16932), the `TARGET_PDB_FILE` is for linker PDB files, however, static libraries need compiler PDB files. I think it does not make sense to deploy those, so changing above `if(MSVC)` to the following may be a solution:
```
if(MSVC AND BUILD_SHARED_LIBS)
  install(FILES $<TARGET_PDB_FILE:OIS> DESTINATION bin OPTIONAL)
endif(MSVC AND BUILD_SHARED_LIBS)
```
Do you think this is a valid solution? If so, should I add a pull request for the fix?

**Comment by Ybalrid** [comment]
That's probably valid. It is useful to install PDB files if you want to debug code from inside the library, but if this mitigate your problem, do not hesitate to pull request that change! 😁

**Comment by Ybalrid** [comment]
closing, see changes in #58
