### ISSUE TITLE
Can't compile on linux.

### ISSUE THREAD

**Issue by mrseth** [wgois/OIS#8]
I execute ./bootstrap && ./configure && make and get the following error:

make[1]: Entering directory `/run/media/sergio/RAZIEL/OIS/src'
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../includes  -I../includes -g -O2 -I/usr/X11R6/include    -g -O2 -MT OISInputManager.lo -MD -MP -MF .deps/OISInputManager.Tpo -c -o OISInputManager.lo OISInputManager.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../includes -I../includes -g -O2 -I/usr/X11R6/include -g -O2 -MT OISInputManager.lo -MD -MP -MF .deps/OISInputManager.Tpo -c OISInputManager.cpp  -fPIC -DPIC -o .libs/OISInputManager.o
In file included from OISInputManager.cpp:23:0:
../includes/OISInputManager.h:207:17: error: cannot declare parameter '<anonymous>' to be of abstract type 'OIS::InputManager'
   InputManager& operator=(InputManager);
                 ^
../includes/OISInputManager.h:38:19: note:   because the following virtual functions are pure within 'OIS::InputManager':
  class _OISExport InputManager
                   ^
../includes/OISInputManager.h:174:16: note: 	virtual void OIS::InputManager::_initialize(OIS::ParamList&)
   virtual void _initialize(ParamList &paramList) = 0;

**Comment by andrewfenn** [comment]
It's a bug in the current code base you need to edit that line to look like this:

```
InputManager& operator=(const InputManager&);
```

Otherwise you can look at my cmake fork available [here](https://github.com/andrewfenn/OIS/tree/cmake)

**Comment by TheOnlyJoey** [comment]
Will fix this with a couple of bugfixes we did internally this week

**Comment by TheOnlyJoey** [comment]
This is fixed in the latest version.
