### ISSUE TITLE
Native OpenXR Support

### ISSUE THREAD

**Issue by xypherorion** [wgois/OIS#86]
Support for OpenXR Devices through the Khronos group standards in order to support motion controllers, HMDs, and future devices.

https://registry.khronos.org/OpenXR/specs/1.0/man/html/openxr.html

**Comment by Ybalrid** [comment]
Hi Xypher!

OpenXR's inputs is action-system and is probably too foreign to translate to the API of OIS, so I am not sure this idea is too relevant. It is action-driven, and a lot closer to a generalized version of SteamInput than a "check that button X has been pressed" sort of API.

The way it is supposed to work is more akin to a "define a pet the cat action, then register an input binding for controller X, Y and Z" (And a Runtime that support controller W you did not know about should provide a mapping, or a way for the user to set it)
